Kaydunov_EH1T1
javaGuruBY/rpaS3 pull request #10
Opened 2021-02-11 20:19 UTC by GardDen

2021-02-13 12:05 UTC, AlexMackevich submitted a review, later dismissed

2021-02-13 21:10 UTC, gornovanton1992 requested changes
please, finish task

2021-02-13 21:11 UTC, gornovanton1992 approved these changes

2021-02-14 09:20 UTC, AlenaPalasionak approved these changes
lgfm

2021-02-14 22:43 UTC, GardDen commented
> please, finish task

Finished.

2021-02-15 05:20 UTC, GardDen commented
> lgfm

Алена, ты просмотрела реквест но не апрувнула.

2021-02-15 19:21 UTC, NikaLu reviewed
Need to correct

2021-02-15 19:34 UTC, GardDen commented
> Need to correct
What I must to correct?

2021-02-15 19:49 UTC, VasiliZas approved these changes

2021-02-15 20:03 UTC, NikaLu reviewed
> This is first lesson english.

> My home work will there soon.

2021-02-15 20:03 UTC, NikaLu commented on homework/english/kaydunov/lecture1/task1.md
> +Yes, I learn English before. I wont improve my speaking English. The hardest thing about learning English is speaking English.
I want to improve my spoken language.

2021-02-15 20:11 UTC, AnzhelaKhamitskaya submitted a review, later dismissed

2021-02-15 20:27 UTC, GardDen commented on homework/english/kaydunov/lecture1/task1.md
> +This is first lesson english.
- [ ]

2021-02-15 20:31 UTC, GardDen commented on homework/english/kaydunov/lecture1/task1.md
> +My home work will there soon.
+

2021-02-15 21:02 UTC, AnzhelaKhamitskaya approved these changes

2021-02-15 21:16 UTC, NikaLu approved these changes

2021-02-16 07:26 UTC, shpaser2 approved these changes
Lgfm

2021-02-16 10:15 UTC, merged