Revert 124 alexandr kas jh1
javaGuruBY/rpaS3 pull request #127
Opened 2021-02-18 15:09 UTC by Sarmat92

2021-02-18 15:22 UTC, Donutella-tech reviewed
А чего дз не полное?

2021-02-19 05:18 UTC, GardDen requested changes

2021-02-19 05:18 UTC, GardDen commented on homework/english/alexandr_kas/lecture1/tassk1.md
> +6  — What does your sister do?
А где 7 пункт?

2021-02-19 16:07 UTC, Sarmat92 commented on homework/english/alexandr_kas/lecture1/tassk1.md
> +6  — What does your sister do?
готово.

2021-02-19 19:19 UTC, 2LAI approved these changes
lgfm

2021-02-19 19:26 UTC, nanita-na-na approved these changes
good

2021-02-19 19:30 UTC, alqaesi approved these changes

2021-05-26 23:34 UTC, KaydunovDenis approved these changes

2021-05-26 23:35 UTC, closed without merging

2021-05-26 23:35 UTC, KaydunovDenis commented
Not relevant.