Main
javaGuruBY/rpaS3 pull request #128
Opened 2021-02-18 16:22 UTC by Sarmat92

add full EH

2021-02-18 17:15 UTC, anastasiaasadcheva94 commented on homework/english/alexandr_kas/lecture1/tassk1.md
> +4 What do you do? - I doing my english homework
What do you do? - используется для того, чтобы спросить, кто человек по профессии. What **_are_** you **_doing_**? – Что ты делаешь? (в данный момент)

2021-02-18 17:15 UTC, anastasiaasadcheva94 commented on homework/java/alexandrKas/task2.md
> +}
Можно еще реализовать ввод данных пользователем.

2021-02-19 05:17 UTC, GardDen requested changes
Исправь замечания

2021-02-19 15:40 UTC, Sarmat92 commented on homework/english/alexandr_kas/lecture1/tassk1.md
> +1 Are you usually working on Saturdays? -> Do you usually working on Saturdays?
done)

2021-02-19 15:40 UTC, Sarmat92 commented on homework/english/alexandr_kas/lecture1/tassk1.md
> +6 What happened? Why do you cry? -> What happened? Why do you crying?
yeap

2021-02-19 15:40 UTC, Sarmat92 commented on homework/english/alexandr_kas/lecture1/tassk1.md
> +2 I [am] go to the gym on Mondays because I usually finish my work very late.
done.

2021-02-19 15:41 UTC, Sarmat92 commented on homework/english/alexandr_kas/lecture1/tassk1.md
> +3 Please turn off the laptop, you [are] using it.
done

2021-02-19 15:41 UTC, Sarmat92 commented on homework/english/alexandr_kas/lecture1/tassk1.md
> +4 I [do] like tea, but today, I [am] drinking it.
done

2021-02-19 15:41 UTC, Sarmat92 commented on homework/english/alexandr_kas/lecture1/tassk1.md
> +4 What do you do? - I doing my english homework
done

2021-02-19 15:50 UTC, anastasiaasadcheva94 submitted a review, later dismissed
Good job 👍

2021-02-19 16:21 UTC, anastasiaasadcheva94 approved these changes

2021-02-22 12:15 UTC, yurasava approved these changes

2021-03-06 13:17 UTC, KaydunovDenis approved these changes

2021-03-06 13:18 UTC, merged