YAKIMUK_EH1T2
javaGuruBY/rpaS3 pull request #17
Opened 2021-02-12 10:56 UTC by vitya771

2021-02-12 11:24 UTC, 2LAI approved these changes

2021-02-12 18:35 UTC, GardDen reviewed
Я не принимаю твой запрос. Потому что домашка по английскому не сделана. Текст домашки находится в репозитории джавагуру в папке english

2021-02-16 11:36 UTC, GardDen requested changes
Как будет сделано полностью, тогда I will approve your pullrequest.

2021-02-17 08:12 UTC, BulavaKatsyaryna approved these changes

2021-05-26 23:32 UTC, KaydunovDenis commented
Not relevant.

2021-05-26 23:32 UTC, closed without merging