HW2T1 has been done
javaGuruBY/rpaS3 pull request #51
Opened 2021-02-14 10:49 UTC by VasiliZas

2021-02-14 13:51 UTC, natasha-shev approved these changes

2021-02-14 14:22 UTC, anastasiaasadcheva94 submitted a review, later dismissed
lgfm

2021-02-14 15:23 UTC, GardDen commented on homework/java/vasili_zasinets/HW2/HW2T1.md
> +Количество кораблей в порту    - ship
ship - это скорее корабль как объект? c заданными характеристиками? переменная должна четка характеризовать переменную
я думаю лучше - countShip

2021-02-14 15:24 UTC, GardDen commented on homework/java/vasili_zasinets/HW2/HW2T1.md
> +Счетчик целых чисел            - nint
слова нужно разделять
nInt or n_int

2021-02-14 15:25 UTC, GardDen commented on homework/java/vasili_zasinets/HW2/HW2T1.md
> +Введеное число пользователем   - insnuser
аналогичное замечание как и к п.5

2021-02-14 15:26 UTC, GardDen requested changes
После исправления, приму.

2021-02-14 16:13 UTC, VasiliZas commented on homework/java/vasili_zasinets/HW2/HW2T1.md
> +Введеное число пользователем   - insnuser
все исправлено

2021-02-14 16:18 UTC, VasiliZas commented
> lgfm

пересмотри еще раз. внес изменения

2021-02-15 12:29 UTC, vitya771 approved these changes

2021-02-15 12:34 UTC, yurasava approved these changes

2021-02-15 13:43 UTC, GardDen approved these changes

2021-02-15 13:54 UTC, merged