English HW1 T1 has been done
javaGuruBY/rpaS3 pull request #56
Opened 2021-02-14 14:27 UTC by anastasiaasadcheva94

2021-02-14 14:54 UTC, VasiliZas approved these changes

2021-02-14 15:29 UTC, GardDen requested changes
Я не понимаю как ответ ты выбрал. Который с тильдами или без.

2021-02-14 16:09 UTC, anastasiaasadcheva94 commented
> Я не понимаю какой ответ ты выбрал. Который с тильдами или без.

c тильдами -  зачеркнутый.  Посмотри еще раз, пожалуйста.

2021-02-14 16:16 UTC, VasiliZas approved these changes
мне норм

2021-02-15 12:22 UTC, yurasava approved these changes

2021-02-15 12:34 UTC, Donutella-tech requested changes
read notes

2021-02-15 12:34 UTC, Donutella-tech commented on homework/english/anastasia_asadcheva/lesson1/hometask1.md
> +1. *Do* you usually working on Saturdays?
work

2021-02-15 12:34 UTC, Donutella-tech commented on homework/english/anastasia_asadcheva/lesson1/hometask1.md
> +5. — Where are you from?
Where do you come from

2021-02-15 12:34 UTC, Donutella-tech commented on homework/english/anastasia_asadcheva/lesson1/hometask1.md
> +3. He's needing a moral support.
He needs

2021-02-15 12:43 UTC, closed without merging

2021-02-15 12:45 UTC, Uchukaknado commented
The corrections are right. Well done, guys!