Home work is ready.
javaGuruBY/rpaS3 pull request #96
Opened 2021-02-15 22:12 UTC by VovaShylymov

2021-02-16 07:16 UTC, shpaser2 reviewed
Part 3 - хотя бы словосочетания со словами которые переводили составить надо.

2021-02-16 10:21 UTC, GardDen requested changes
Нужно домашку сделать сперва, а потом просить апрувы. В чате английского есть презентация по этому уроку.

2021-02-16 10:21 UTC, GardDen commented on homework/english/Vova_Shylymov/Lecture1/task1.md
> +7 Did you learn English before? Would you like to improve your English? What is the hardest thing about learning English?
where are your answers?

2021-02-16 10:21 UTC, GardDen commented on homework/english/Vova_Shylymov/Lecture1/task1.md
> +MAKE YOUR OWN EXAMPES WITH THE VOCABULARY OF THE SECTION (ПОСТРОЙТЕ СВОИ ПРЕДЛОЖЕНИЯ СО СЛОВАМИ ИЗ СЕКЦИИ).
Where are your answers?

2021-02-16 20:45 UTC, GardDen approved these changes, later dismissed

2021-05-26 23:30 UTC, closed without merging

2021-05-26 23:31 UTC, KaydunovDenis commented
Not relevant.